export const STORAGE_KEY = "buttonizer_saved_buttons";

export const state = {
  detectedButtons: [],
  savedButtons: [],
  pageTitle: "No page scanned yet",
  pageUrl: "Scan a page to inspect visible buttons",
  status: "Idle",
  detectedIndex: 0,
  selectedSavedId: null,
  toastTimer: null,
};

export const elements = {
  scanPageButton: document.getElementById("scanPageButton"),
  saveAllButton: document.getElementById("saveAllButton"),
  saveCurrentButton: document.getElementById("saveCurrentButton"),
  clearLibraryButton: document.getElementById("clearLibraryButton"),
  exportArchiveButton: document.getElementById("exportArchiveButton"),
  archivePrevButton: document.getElementById("archivePrevButton"),
  archiveNextButton: document.getElementById("archiveNextButton"),
  archiveCountBadge: document.getElementById("archiveCountBadge"),
  capturePrevButton: document.getElementById("capturePrevButton"),
  captureNextButton: document.getElementById("captureNextButton"),
  removeSavedButton: document.getElementById("removeSavedButton"),
  copySavedCssButton: document.getElementById("copySavedCssButton"),
  copyMarkupButton: document.getElementById("copyMarkupButton"),
  statusMessage: document.getElementById("statusMessage"),
  toastMessage: document.getElementById("toastMessage"),
  scanLoader: document.getElementById("scanLoader"),
  scanCountBadge: document.getElementById("scanCountBadge"),
  pageFacts: document.getElementById("pageFacts"),
  detectedEmpty: document.getElementById("detectedEmpty"),
  detectedInspector: document.getElementById("detectedInspector"),
  inspectorTitle: document.getElementById("inspectorTitle"),
  inspectorSubtitle: document.getElementById("inspectorSubtitle"),
  inspectorPreview: document.getElementById("inspectorPreview"),
  inspectorSize: document.getElementById("inspectorSize"),
  inspectorFont: document.getElementById("inspectorFont"),
  inspectorWeight: document.getElementById("inspectorWeight"),
  inspectorBackground: document.getElementById("inspectorBackground"),
  inspectorText: document.getElementById("inspectorText"),
  inspectorBorder: document.getElementById("inspectorBorder"),
  inspectorRadius: document.getElementById("inspectorRadius"),
  inspectorShadow: document.getElementById("inspectorShadow"),
  inspectorPalette: document.getElementById("inspectorPalette"),
  inspectorSelector: document.getElementById("inspectorSelector"),
  inspectorMarkup: document.getElementById("inspectorMarkup"),
  savedDetailsCss: document.getElementById("savedDetailsCss"),
  savedEmpty: document.getElementById("savedEmpty"),
  savedLibrary: document.getElementById("savedLibrary"),
  savedPreview: document.getElementById("savedPreview"),
  savedDetails: document.getElementById("savedDetails"),
  savedDetailsTitle: document.getElementById("savedDetailsTitle"),
  savedDetailsFont: document.getElementById("savedDetailsFont"),
  savedDetailsBackground: document.getElementById("savedDetailsBackground"),
  savedDetailsBorder: document.getElementById("savedDetailsBorder"),
  savedDetailsShadow: document.getElementById("savedDetailsShadow"),
  savedDetailsPalette: document.getElementById("savedDetailsPalette"),
  appVersion: document.getElementById("appVersion"),
};
